# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class CheckCriteriaRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, content_ids=None, query=None):  # noqa: E501
        """CheckCriteriaRequest - a model defined in OpenAPI

        :param content_ids: The content_ids of this CheckCriteriaRequest.  # noqa: E501
        :type content_ids: List[str]
        :param query: The query of this CheckCriteriaRequest.  # noqa: E501
        :type query: object
        """
        self.openapi_types = {
            'content_ids': List[str],
            'query': object
        }

        self.attribute_map = {
            'content_ids': 'content_ids',
            'query': 'query'
        }

        self._content_ids = content_ids
        self._query = query

    @classmethod
    def from_dict(cls, dikt) -> 'CheckCriteriaRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CheckCriteriaRequest of this CheckCriteriaRequest.  # noqa: E501
        :rtype: CheckCriteriaRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def content_ids(self):
        """Gets the content_ids of this CheckCriteriaRequest.


        :return: The content_ids of this CheckCriteriaRequest.
        :rtype: List[str]
        """
        return self._content_ids

    @content_ids.setter
    def content_ids(self, content_ids):
        """Sets the content_ids of this CheckCriteriaRequest.


        :param content_ids: The content_ids of this CheckCriteriaRequest.
        :type content_ids: List[str]
        """

        self._content_ids = content_ids

    @property
    def query(self):
        """Gets the query of this CheckCriteriaRequest.


        :return: The query of this CheckCriteriaRequest.
        :rtype: object
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this CheckCriteriaRequest.


        :param query: The query of this CheckCriteriaRequest.
        :type query: object
        """

        self._query = query
