# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class User(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None, session_ids=None):  # noqa: E501
        """User - a model defined in OpenAPI

        :param user_id: The user_id of this User.  # noqa: E501
        :type user_id: str
        :param session_ids: The session_ids of this User.  # noqa: E501
        :type session_ids: List[str]
        """
        self.openapi_types = {
            'user_id': str,
            'session_ids': List[str]
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'session_ids': 'session_ids'
        }

        self._user_id = user_id
        self._session_ids = session_ids

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self):
        """Gets the user_id of this User.


        :return: The user_id of this User.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this User.


        :param user_id: The user_id of this User.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def session_ids(self):
        """Gets the session_ids of this User.


        :return: The session_ids of this User.
        :rtype: List[str]
        """
        return self._session_ids

    @session_ids.setter
    def session_ids(self, session_ids):
        """Sets the session_ids of this User.


        :param session_ids: The session_ids of this User.
        :type session_ids: List[str]
        """

        self._session_ids = session_ids
