version: '3.3'
services:
  reverse-proxy:
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
  conso-api:
    labels:
      - "traefik.http.routers.conso-api.rule=host(`conso-api.localhost`) && path(`/dataviz-api/v1/{id:.*}`)"
    environment:
      - LOG_LEVEL=debug
      - APP_ENV=dev
