version: "3.6"

services:
  web:
    build: .
    command: bash -c "/app/flask-run.sh" 
    working_dir: /discoverability
    depends_on:
      - db
    volumes:
      - .:/discoverability
    env_file:
      - env_files/.env.development
    ports:
      - "8000:8000"
  db:
    image: postgres:11.4
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - env_files/.env.development
    ports:
      - "5432:5432"

volumes:
  postgres:

networks:
  default:
    driver: bridge
