version: '3.3'
services:
  reverse-proxy:
    image: traefik:v2.2
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--accesslog=true"
      - "--log.level=WARN"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  conso-api:
    image: discoverability/conso-api
    labels:
     - "traefik.enable=true"
  conso-api-legacy:
    image: discoverability/conso-api
    labels:
     - "traefik.enable=true"




