version: '3.3'
services:
  reverse-proxy:
    image: traefik:v2.2
    command: 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=contact@vod-prime.space"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
  conso-api:
    labels:
      - "traefik.http.routers.conso-api.rule=host(`experimental-api.vod-prime.space`) && path(`/dataviz-api/v1/{id:.*}`)"
      - "traefik.http.routers.conso-api.tls.certresolver=myresolver"
    environment:
      - LOG_LEVEL=debug
      - APP_ENV=production
      - SQLALCHEMY_DATABASE_URI=mysql://discoverability:aWuathigh8Ui@ts236797-001.dbaas.ovh.net:35824/discoverability
      - WORKERS_PER_CORE=1
